# Generated by Django 3.1.1 on 2020-09-19 15:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('h_name', models.CharField(max_length=220)),
                ('h_address', models.CharField(max_length=220)),
                ('r_price', models.DecimalField(decimal_places=2, max_digits=11)),
                ('hotel_rooms', models.IntegerField()),
                ('h_image', models.ImageField(upload_to='Hotel images')),
                ('h_country', models.CharField(max_length=220)),
                ('h_mobile', models.CharField(max_length=20)),
                ('h_location', models.CharField(max_length=220)),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('m_contact', models.CharField(max_length=300)),
                ('m_mobile', models.CharField(max_length=15)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Resturant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('r_name', models.CharField(max_length=220)),
                ('r_address', models.CharField(max_length=220)),
                ('r_image', models.ImageField(upload_to='Hotel images')),
                ('r_menu_image', models.ImageField(upload_to='menue images')),
                ('r_country', models.CharField(max_length=220)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('open_at', models.DateTimeField()),
                ('close_at', models.DateTimeField()),
                ('r_mobile', models.CharField(max_length=20)),
                ('t_location', models.CharField(max_length=220)),
            ],
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('t_destination', models.CharField(max_length=250)),
                ('t_price', models.DecimalField(decimal_places=2, max_digits=11)),
                ('T_country', models.CharField(max_length=220)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('start_at', models.DateTimeField()),
                ('end_at', models.DateTimeField()),
                ('t_mobile', models.CharField(max_length=20)),
                ('t_location', models.CharField(max_length=220)),
                ('t_members', models.ManyToManyField(to='dashboard.Member')),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_name', models.CharField(max_length=220)),
                ('c_hotels', models.ManyToManyField(to='dashboard.Hotel')),
                ('c_resturants', models.ManyToManyField(to='dashboard.Resturant')),
                ('c_trips', models.ManyToManyField(to='dashboard.Trip')),
            ],
        ),
    ]
