# Generated by Django 3.1.1 on 2020-09-19 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='c_image',
            field=models.ImageField(null=True, upload_to='countries'),
        ),
    ]
