# Generated by Django 3.1.1 on 2020-09-19 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_country_c_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='t_image',
            field=models.ImageField(null=True, upload_to='Hotel images'),
        ),
    ]
