# Generated by Django 3.1.1 on 2020-09-19 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_trip_t_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resturant',
            name='close_at',
        ),
        migrations.RemoveField(
            model_name='resturant',
            name='open_at',
        ),
        migrations.AlterField(
            model_name='trip',
            name='t_image',
            field=models.ImageField(null=True, upload_to='trip images'),
        ),
    ]
