# Generated by Django 3.1.1 on 2020-09-19 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_auto_20200919_2256'),
    ]

    operations = [
        migrations.AddField(
            model_name='resturant',
            name='close_at',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='resturant',
            name='open_at',
            field=models.TimeField(null=True),
        ),
    ]
