# Generated by Django 3.1.1 on 2020-09-20 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_auto_20200919_2257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='c_hotels',
            field=models.ManyToManyField(blank=True, to='dashboard.Hotel'),
        ),
        migrations.AlterField(
            model_name='country',
            name='c_resturants',
            field=models.ManyToManyField(blank=True, to='dashboard.Resturant'),
        ),
        migrations.AlterField(
            model_name='country',
            name='c_trips',
            field=models.ManyToManyField(blank=True, to='dashboard.Trip'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='t_members',
            field=models.ManyToManyField(blank=True, to='dashboard.Member'),
        ),
    ]
