# Generated by Django 3.1.1 on 2020-09-20 19:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_auto_20200920_1749'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='user',
        ),
        migrations.AddField(
            model_name='member',
            name='m_age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='m_gender',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='m_id',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='m_name',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='m_mobile',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.CreateModel(
            name='trip_reservations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reservation_date', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cancelation_date', models.DateTimeField()),
                ('member', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.member')),
                ('trip', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.trip')),
            ],
        ),
        migrations.CreateModel(
            name='resturant_reservations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reservation_date', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cancelation_date', models.DateTimeField()),
                ('member', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.member')),
                ('resturant', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.resturant')),
            ],
        ),
        migrations.CreateModel(
            name='Hotel_reservations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reservation_date', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cancelation_date', models.DateTimeField()),
                ('hotel', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.hotel')),
                ('member', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.member')),
            ],
        ),
    ]
