# Generated by Django 3.1.1 on 2020-09-20 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_auto_20200920_2311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel_reservations',
            name='cancelation_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='resturant_reservations',
            name='cancelation_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trip_reservations',
            name='cancelation_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
